version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - hr-finder-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=hrfinder
      - SECRET_KEY=your-secret-key
      - AUTH_SECRET=your-auth-secret
    networks:
      - hr-finder-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=hrfinder
    volumes:
      - mongodb_data:/data/db

  mongodb_test:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=hrfinder_test

networks:
  hr-finder-network:
    driver: bridge

volumes:
  mongodb_data:
