version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - hr-finder-network

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - MONGODB_URL=mongodb+srv://admin:admin@hrfinder.rt8ed.mongodb.net/HRFinder
      - MONGODB_DB_NAME=HRFinder
      - DEBUG=True
    networks:
      - hr-finder-network
    restart: always

networks:
  hr-finder-network:
    driver: bridge

volumes:
  mongodb_data:
